cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name="cart"),
    path('success/', views.success, name="success"),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'


urlpatterns = [
    path('', views.frontpage, name="home"),
    path('contact-us/', views.contactpage, name="contact"),
]

order/urls.py
from django.urls import path


app_name = 'order'


urlpatterns = [
    
]

simple_multivendor_site/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('vendor/', include('vendor.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models

# Create your models here.

order/models.py
from django.db import models
from product.models import Product
from vendor.models import Vendor

# Create your models here.
class Order(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100) 
    email = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=100)
    place = models.CharField(max_length=100)
    phone = models.CharField(max_length=100) 
    created_at = models.DateTimeField(auto_now_add=True)
    paid_amount = models.DecimalField(max_digits=8, decimal_places=2)
    vendors = models.ManyToManyField(Vendor, related_name="orders")

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.first_name

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name="items", on_delete=models.CASCADE)
    vendor = models.ForeignKey(Vendor, related_name="items", on_delete=models.CASCADE)
    vendor_paid = models.BooleanField(default=False)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_total_price(self):
        return self.price * self.quantity

cart/forms.py
from django import forms
from django.forms.fields import CharField 

class CheckoutForm(forms.Form):
    first_name = forms.CharField(max_length=255)
    last_name = forms.CharField(max_length=255)
    email = forms.EmailField(max_length=255)
    phone = forms.CharField(max_length=255)
    address = forms.CharField(max_length=255)
    zipcode = forms.CharField(max_length=255)
    place = forms.CharField(max_length=255)
    stripe_token = forms.CharField(max_length=255)


    

product/forms.py
from django import forms
from django.forms.fields import IntegerField
from django.forms.forms import Form


class AddToCartForm(forms.Form):
    quantity = forms.IntegerField()

cart/views.py
import stripe #pip install stripe 

from django. conf import settings
from django.contrib import messages
from django.shortcuts import redirect, render
from .cart import Cart
from .forms import CheckoutForm

from order.utilities import checkout, notify_vendor, notify_customer

# Create your views here.
def cart_detail(request):
    cart = Cart(request)

    # If Checkout
    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        if form.is_valid():
            stripe.api_key = settings.STRIPE_SECRET_KEY

            stripe_token = form.cleaned_data['stripe_token']

            try:
                charge = stripe.Charge.create(
                    amount=int(cart.get_total_cost() * 100), # Amount in Cents
                    currency='USD',
                    description='Charge From Multivendor Shop',
                    source=stripe_token
                )

                first_name = form.cleaned_data['first_name']
                last_name = form.cleaned_data['last_name']
                email = form.cleaned_data['email']
                phone = form.cleaned_data['phone']
                address = form.cleaned_data['address']
                zipcode = form.cleaned_data['zipcode']
                place = form.cleaned_data['place']

                order = checkout(request, first_name, last_name, email, phone, address, zipcode, place, cart.get_total_cost())

                cart.clear()

                # SEnd Email Notification
                notify_customer(order)
                notify_vendor(order)

                return redirect('cart:success')
            
            except Exception:
                messages.error(request, "Something went wrong with payment.")
            
    else:
        form = CheckoutForm()

    remove_from_cart = request.GET.get('remove_from_cart', '')
    change_quantity = request.GET.get('change_quantity', '')
    quantity = request.GET.get('quantity', 0)

    if remove_from_cart:
        cart.remove(remove_from_cart)
        return redirect('cart:cart')
    
    if change_quantity:
        cart.add(change_quantity, quantity, True)
        return redirect('cart:cart')
        
    return render(request, 'cart/cart.html', {'form': form, 'stripe_pub_key': settings.STRIPE_PUB_KEY})


def success(request):
    return render(request, 'cart/success.html')

core/views.py
from django.shortcuts import render
from product.models import Product

# Create your views here.

def frontpage(request):
    newest_products = Product.objects.all()[0:8]
    context = {
        'newest_products': newest_products,
    }
    return render(request, 'core/frontpage.html', context)


def contactpage(request):
    return render(request, 'core/contact.html')

order/views.py
from django.shortcuts import render

# Create your views here.

templates/cart/cart.html
{% extends 'core/base.html' %}

{% block title %}Cart{% endblock title %}

{% block content %}

    <h1 class="title">Cart</h1>

    {% if cart %}
    
        <div class="box mb-6">
            <div class="table">
                <table class="table is-fullwidth is-striped">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Product</th>
                            <th>Quantity</th>
                            <th>Price</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for item in cart %}
                        
                            <tr>
                                <td>
                                    <figure class="image is-64x64">
                                        <img src="{{ item.product.get_thumbnail }}" alt="{{item.product.title}}">
                                    </figure>
                                </td>
                                <td>
                                    <a href="{% url 'product:product' item.product.category.slug item.product.slug %}">{{item.product.title}}</a>
                                </td>
                                <td>
                                    ${{item.quantity}}

                                    <a href="?change_quantity={{ item.id }}&quantity=-1">-</a>
                                    <a href="?change_quantity={{ item.id }}&quantity=1">+</a>

                                </td>

                                <td>${{ item.total_price }}</td>
                                <td>
                                    <a href="?remove_from_cart={{item.id}}" class="delete">Remove</a>
                                </td>
                            </tr>
                        
                        {% endfor %}
                    </tbody>

                    <tfoot>
                        <tr>
                            <td></td>
                            <td><strong>Total Cost</strong> </td>
                            <td><strong>{{ cart|length }}</strong> </td>
                            <td colspan="2">${{cart.get_total_cost}}</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>


        <h2 class="subtitle">Contact Information</h2>

        <form method="post" action="" id="payment-form">
            {% csrf_token %}

            {% if form.non_field_errors %}
                <div class="notification is-danger">
                    {{form.non_field_errors}}
                </div>
            {% endif %}

            {% if form.errors %}
                <div class="notification is-danger">
                    <ul>
                        {% for field in form %}
                            {% for error in field.errors %}
                                <li><strong>{{field.label}}</strong>{{error}}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            <div class="columns">
                <div class="column is-6">
                    <div class="field">
                        <label>First Name</label>

                        <div class="control">
                            <input type="text" name="first_name" id="" class="input">
                        </div>
                    </div>

                    <div class="field">
                        <label>Last Name</label>

                        <div class="control">
                            <input type="text" name="last_name" id="" class="input">
                        </div>
                    </div>

                    <div class="field">
                        <label>Email</label>

                        <div class="control">
                            <input type="email" name="email" id="" class="input">
                        </div>
                    </div>

                    <div class="field">
                        <label>Phone</label>

                        <div class="control">
                            <input type="text" name="phone" id="" class="input">
                        </div>
                    </div>

                </div>

                <div class="column is-6">
                    <div class="field">
                        <label>Address</label>

                        <div class="control">
                            <input type="text" name="address" id="" class="input">
                        </div>
                    </div>

                    <div class="field">
                        <label>Zip Code</label>

                        <div class="control">
                            <input type="text" name="zipcode" id="" class="input">
                        </div>
                    </div>

                    <div class="field">
                        <label>Place</label>

                        <div class="control">
                            <input type="text" name="place" id="" class="input">
                        </div>
                    </div>

                </div>

            </div>


            <h2 class="subtitle">Payment Information</h2>

            <div id="card-element">
                {% comment %} A stripe Element will be inserted here {% endcomment %}
            </div>

            {% if messages %}
                {% for message in messages %}
                    <div class="notification is-danger">
                        {{message}}
                    </div>
                {% endfor %}
            {% endif %}

            <div class="field">
                <div class="control">
                    <button class="button is-dark mt-4 is-uppercase">Checkout</button>
                </div>
            </div>
        </form>
    {% else %}

    <p>You don't have any products in your cart.</p>

    {% endif %}

{% endblock content %}


{% block scripts %}

    <script src="https://js.stripe.com/v3/"></script>
    <script>
        var stripe = Stripe('{{ stripe_pub_key }}');
        var elements = stripe.elements();

        var card = elements.create('card');

        card.mount('#card-element');

        var form = document.getElementById('payment-form');
        form.addEventListener('submit', function(event) {
            event.preventDefault();

            stripe.createToken(card).then(function(result) {
                if (result.error) {
                    var errorElement = document.getElementById('card-errors');
                    errorElement.textContent = result.error.message;
                } else {
                    stripeTokenHandler(result.token);
                }
            });
        });

        function stripeTokenHandler(token) {
            var form = document.getElementById('payment-form');
            var hiddenInput = document.createElement('input');
            hiddenInput.setAttribute('type', 'hidden');
            hiddenInput.setAttribute('name', 'stripe_token');
            hiddenInput.setAttribute('value', token.id);
            form.appendChild(hiddenInput);

            form.submit();
        }
    </script>

{% endblock scripts %}

templates/cart/success.html
{% extends 'core/base.html' %}

{% block title %}Order Successful{% endblock title %}

{% block content %}

    <h1 class="title">Thanks for the order.</h1>

{% endblock content %}

templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %}Multi Vendor E-Commerce Website{% endblock title %} </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">

</head>
<body>

    <div class="container">
        <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="{% url 'core:home' %}">
                Beginners Hut
                </a>

                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-start">
                <a class="navbar-item" href="{% url 'core:home' %}">
                    Home
                </a>
                
                {% for category in categories %}
                    <a class="navbar-item" href="{% url 'product:category' category.slug %}">
                        {{category.title}}
                    </a>
                {% endfor %}

                

                </div>

                <div class="navbar-start">
                    <div class="navbar-item">
                        <form method="get" action="{% url 'product:search' %}">
                            <div class="field has-addons">
                                <div class="control">
                                    <input type="search" name="query" id="" class="input" placeholder="Search...">
                                </div>
                                <div class="control">
                                    <button class="button is-dark is-uppercase">Search</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="navbar-end">

                <div class="navbar-item">
                    <a href="{% url 'cart:cart' %}" class="button is-warning">Cart {% if cart %}({{cart|length}}){% endif %}</a>
                </div>
                
                {% if request.user.is_authenticated %}

                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link is-capitalized">
                    {{user.vendor.name}}
                    </a>

                    <div class="navbar-dropdown">
                    <a class="navbar-item" href="{% url 'vendor:vendor-admin' %}">
                        Profile
                    </a>
                    <a class="navbar-item" href="{% url 'vendor:edit-vendor' %}">
                        Update Profile
                    </a>
                    <a class="navbar-item" href="{% url 'vendor:add-product' %}">
                        Add Product
                    </a>
                    <hr class="navbar-divider">
                    <a class="navbar-item" href="{% url 'vendor:logout' %}">
                        Logout
                    </a>
                    </div>
                </div>

                {% else %}

                <div class="navbar-item">
                    <div class="buttons">
                        <a class="button is-primary" href="{% url 'vendor:become-vendor' %}">
                            <strong>Become Vendor</strong>
                        </a>
                        <a class="button is-light" href="{% url 'vendor:login' %}">
                            Log in
                        </a>
                    </div>
                </div>

                {% endif %}


                </div>
            </div>
            </nav>
    </div>
    
    <section class="section">
        <div class="container">

            {% block content %}{% endblock content %}

        </div>
    </section>

    
    <footer class="footer">
        <div class="container">
            <h3 class="is-size-4 mb-4">Multi Vendor E-Commerce</h3>
            
            {% if request.user.is_authenticated %}
                <a href="{% url 'vendor:vendor-admin' %}">Vendor Admin</a>
            {% else %}
                <a href="{% url 'vendor:become-vendor' %}">Become a Vendor</a>
            {% endif %}

            <br>
            <a href="{% url 'vendor:vendors' %}">All Vendors</a>

        </div>
    </footer>

    <script src="{% static 'js/main.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}

</body>
</html>

templates/core/contact.html
{% extends 'core/base.html' %}


{% block title %}Contact Us{% endblock title %}

{% block content %}

    <h1>Contact Us</h1>

    

{% endblock content %}

templates/core/frontpage.html
{% extends 'core/base.html' %}

{% block title %}Home Page{% endblock title %}

{% block content %}
    <div class="columns is-multiline mb-6">
        <div class="column is-12 has-test-centered mt-6 mb-6">
            <h2 class="is-size-3">Latest Products</h2>
        </div>

        {% for product in newest_products %}
            {% include 'product/parts/list_item.html' %}
        {% endfor %}
    </div>
{% endblock content %}

templates/order/email_notify_customer.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        
        <title>Interiorshop</title>

        <style type="text/css">
            html {
                width: 100%;
            }

            body {
                width: 100%;
                font-family: Arial;
                font-size: 14px;
                background-color: #fff;
                color: #333;
            }
        </style>
    </head>

    <body>
        <table width="100%" cellspacing="0" cellpadding="0">
            <tr>
                <td><h1>New order</h1></td>
            </tr>

            <tr>
                <td>
                    <h3>Details</h3>

                    <b>Name:</b> {{ order.first_name }} {{ order.last_name }}<br>
                    <b>Address:</b> {{ order.address }}<br>
                    <b>Zip and place:</b> {{ order.zipcode }} {{ order.place }}<br>
                    <b>E-mail:</b> {{ order.email }}<br>
                    <b>Phone:</b> {{ order.phone }}
                </td>
            </tr>

            <tr>
                <td>
                    <h3>Products</h3>

                    <table width="100%" cellspacing="0" cellpadding="0">
                        <tr>
                            <td><b>Product</b></td>
                            <td><b>Price</b></td>
                            <td><b>Quantity</b></td>
                            <td><b>Total</b></td>
                        </tr>
                        
                        {% for item in order.items.all %}
                            {% if item.vendor == vendor %}
                                <tr>
                                    <td>{{ item.product.title }}</td>
                                    <td>${{ item.product.price }}</td>
                                    <td>{{ item.quantity }}</td>
                                    <td>${{ item.get_total_price }}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </table>
                </td>
            </tr>
        </table>
    </body>
</html>

templates/order/email_notify_vendor.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        
        <title>Interiorshop</title>

        <style type="text/css">
            html {
                width: 100%;
            }

            body {
                width: 100%;
                font-family: Arial;
                font-size: 14px;
                background-color: #fff;
                color: #333;
            }
        </style>
    </head>

    <body>
        <table width="100%" cellspacing="0" cellpadding="0">
            <tr>
                <td><h1>New order</h1></td>
            </tr>

            <tr>
                <td>
                    <h3>Details</h3>

                    <b>Name:</b> {{ order.first_name }} {{ order.last_name }}<br>
                    <b>Address:</b> {{ order.address }}<br>
                    <b>Zip and place:</b> {{ order.zipcode }} {{ order.place }}<br>
                    <b>E-mail:</b> {{ order.email }}<br>
                    <b>Phone:</b> {{ order.phone }}
                </td>
            </tr>

            <tr>
                <td>
                    <h3>Products</h3>

                    <table width="100%" cellspacing="0" cellpadding="0">
                        <tr>
                            <td><b>Product</b></td>
                            <td><b>Price</b></td>
                            <td><b>Quantity</b></td>
                            <td><b>Total</b></td>
                        </tr>
                        
                        {% for item in order.items.all %}
                            {% if item.vendor == vendor %}
                                <tr>
                                    <td>{{ item.product.title }}</td>
                                    <td>${{ item.product.price }}</td>
                                    <td>{{ item.quantity }}</td>
                                    <td>${{ item.get_total_price }}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </table>
                </td>
            </tr>
        </table>
    </body>
</html>

templates/product/category.html
{% extends 'core/base.html' %}

{% block title %}{{category.title}}{% endblock title %}

{% block content %}
    <div class="columns is-multiline mb-6">
        <div class="column is-12 has-test-centered mt-6 mb-6">
            <h2 class="is-size-3">{{category.title}}</h2>
        </div>

        {% for product in category.products.all %}
            {% include 'product/parts/list_item.html' %}
        {% endfor %}
    </div>
{% endblock content %}

templates/product/parts/list_item.html
<div class="column is-3 product-list-item">
                <div class="box">
                    <figure class="image is-4by3 mb-4">
                        <img src="{{ product.get_thumbnail }}" alt="{{product.title}}">
                    </figure>

                    <h2 class="subtitle">{{product.title}}</h2>

                    <h3 class="price is-size-6 mb-5">${{product.price}}</h3>

                    <hr>

                    <a href="{% url 'product:product' product.category.slug product.slug %}" class="button is-dark is-uppercase">View</a>
                </div>
            </div>

templates/product/product.html
{% extends 'core/base.html' %}

{% block title %}{{product.title}}{% endblock title %}

{% block content %}

    {% if product.image %}
        <figure class="image is-4by3 mb-6">
            <img src="{{product.image.url}}" alt="{{product.title}}">
        </figure>
    {% endif %}

    <h1 class="title">{{product.title}}, ${{product.price}}</h1>

    <p class="mb-6">
        <span class="tag is-dark">{{ product.vendor.name }}</span>
    </p>

    <p>{{product.description}}</p>

    <hr>

    {% if messages %}
        {% for message in messages %}
            <div class="notification is-success is-toast">{{ message }}</div>
        {% endfor %}
    {% endif %}


    <form method="post" action="">
        {% csrf_token %}

        <div class="field has-addons">
            <div class="control">
                <input type="number" name="quantity" value="1" class="input" min="1" id="">
            </div>

            <div class="control">
                <button class="button is-dark is-uppercase">Add to Cart</button>
            </div>
        </div>
    </form>


    {% if similar_products %}
        <hr>

        <div class="columns is-multiline">
            <div class="column is-12">
                <h2 class="subtitle">Similar Products</h2>
            </div>

            {% for product in similar_products %}
                {% include 'product/parts/list_item.html' %}
            {% endfor %}
        </div>
    {% endif %}

{% endblock content %}

templates/product/search.html
{% extends 'core/base.html' %}

{% block title %}Search for {{query}}{% endblock title %}

{% block content %}
    <div class="columns is-multiline mb-6">
        <div class="column is-12 has-test-centered mt-6 mb-6">
            <h2 class="is-size-3"> Search for "{{query}}"</h2>
        </div>

        {% for product in products %}
            {% include 'product/parts/list_item.html' %}
        {% endfor %}
    </div>
{% endblock content %}